import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Sidebar } from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CastMates",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex flex-1 md:flex-row flex-col h-dvh">
            <Sidebar />
            <section className="flex flex-1 h-dvh overflow-y-scroll">
              {children}
            </section>
          </div>
        </Providers>
      </body>
    </html>
  );
}
