import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Sidebar } from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex flex-col h-dvh">
            <div className="flex flex-1">
              <Sidebar />
              <section className="flex-1 h-dvh overflow-y-scroll">
                {children}
              </section>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
